name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: node client.js
    - name: user defined action
      uses: AureaMohammadAlavi/smash-docker-action@v1
      id: hello
      with:
        who-to-greet: 'Mohammad Alavi'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Get the output uid
      run: echo "The time was ${{ steps.hello.outputs.uid }}"      
      
